export const OPERATION_LABELS: Record<string, string> = {
  addProduct: 'Agregar producto',
  updateProduct: 'Actualizar producto',
  deleteProduct: 'Eliminar producto',
  addMovement: 'Registrar movimiento',
  addSale: 'Registrar venta',
  cancelTransit: 'Cancelar tránsito',
  registerWasteFromTransit: 'Registrar merma',
  registerManualConsumption: 'Registrar consumo',
  createPendingAccount: 'Crear cuenta pendiente',
  chargePendingAccount: 'Cobrar cuenta pendiente',
  deletePendingAccount: 'Eliminar cuenta pendiente',
  addItemsToPendingAccount: 'Agregar items a cuenta',
  updatePendingAccountItems: 'Actualizar items de cuenta',
  togglePendingAccountType: 'Cambiar tipo de cuenta',
  createDailyClosing: 'Crear cierre de caja',
  addRecipe: 'Agregar receta',
  updateRecipe: 'Actualizar receta',
  deleteRecipe: 'Eliminar receta',
  updatePendingAccount: 'Actualizar cuenta',
  justifyMovement: 'Justificar movimiento',
  updateAccessPinAttempts: 'Actualizar intentos PIN',
  markPendingAccountPaid: 'Marcar cuenta pagada',
};

export const MODULE_LABELS: Record<string, string> = {
  'inventory': 'Inventario',
  'sales': 'Ventas',
  'closings': 'Cierres de Caja',
  'transit': 'Tránsito',
  'recipes': 'Recetas',
  'employees': 'Empleados',
  'departments': 'Departamentos',
  'payroll': 'Nómina',
  'hr': 'RRHH',
  'accounts': 'Cuentas Pendientes',
  'sync': 'Sincronización',
  'movements': 'Movimientos',
  'settings': 'Configuración',
  'stock': 'Almacén',
  'action-logs': 'Registro de Acciones',
  'consumption': 'Consumo',
  'filtered': 'Centro Filtrado',
  'analysis': 'Análisis',
  'charts': 'Gráficos',
};

export const ACTION_LABELS: Record<string, string> = {
  'CREAR': 'Crear',
  'ELIMINAR': 'Eliminar',
  'ACTUALIZAR': 'Actualizar',
  'MODIFICAR': 'Modificar',
  'ENTRADA': 'Entrada',
  'SALIDA': 'Salida',
  'MERMA': 'Merma',
  'AJUSTE': 'Ajuste',
  'CANCELAR_TRANSITO': 'Cancelar Tránsito',
  'MERMA_TRANSITO': 'Merma en Tránsito',
  'CONSUMO_MANUAL': 'Consumo Manual',
  'COMPENSAR': 'Compensar Sincronización',
  'AGREGAR_ITEMS': 'Agregar Items',
  'ACTUALIZAR_ITEMS': 'Actualizar Items',
  'TOGGLE_TIPO': 'Cambiar Tipo',
  'MARCAR_PAGADO': 'Marcar Pagado',
  'JUSTIFICAR': 'Justificar',
};

export const DETAIL_KEY_TRANSLATIONS: Record<string, string> = {
  product_name: 'Producto',
  quantity: 'Cantidad',
  unit: 'Unidad',
  reason: 'Razón',
  category: 'Categoría',
  total: 'Total',
  items_count: 'Items',
  sale_type: 'Tipo de venta',
  employee: 'Empleado',
  is_account_house: 'Cuenta Casa',
  client_name: 'Cliente',
  recipe_name: 'Receta',
  recipe_id: 'ID Receta',
  new_price: 'Nuevo precio',
  ingredients_count: 'Ingredientes',
  doc_type: 'Tipo doc',
  file_name: 'Archivo',
  doc_name: 'Documento',
  changes: 'Cambios',
  closing_date: 'Fecha de cierre',
  total_sales: 'Ventas totales',
  total_discounts: 'Descuentos',
  total_refunds: 'Devoluciones',
  closing_amount: 'Monto del cierre',
  created_by_name: 'Cerrado por',
  month: 'Mes',
  year: 'Año',
  total_employees: 'Total empleados',
  total_net: 'Neto total',
  employee_name: 'Empleado',
  field: 'Campo',
  old_value: 'Valor anterior',
  new_value: 'Nuevo valor',
  earned_salary: 'Salario Devengado',
  base_salary: 'Salario Básico',
  vacation_days: 'Días de Vacación',
  exemption_base: 'Base Exenta',
  taxable_base: 'Base Imponible',
  tax_amount: 'Impuesto',
  special_contribution: 'Contribución Especial',
  net_salary: 'Salario Neto',
  salary: 'Salario',
  justification: 'Justificación',
  payment_method: 'Método de Pago',
  product_id: 'ID Producto',
  name: 'Nombre',
  sale_id: 'ID Venta',
  transitItemId: 'ID Tránsito',
  productId: 'ID Producto',
  customer: 'Cliente',
  account_id: 'ID Cuenta',
  accountId: 'ID Cuenta',
  id: 'ID',
  type: 'Tipo',
  date: 'Fecha',
  customer_name: 'Cliente',
};
